[package]
name = "usbmux"
version = "0.1.0"
authors = ["lds <lds2012@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"